# Generated by Django 3.2 on 2023-05-11 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=100)),
                ('sum', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_series', models.CharField(max_length=3)),
                ('ticket_nr', models.CharField(max_length=8)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 11, 14, 24, 56, 640816, tzinfo=utc))),
                ('expiry', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 9, 14, 24, 56, 640855, tzinfo=utc))),
            ],
        ),
    ]
