# Generated by Django 3.2 on 2023-04-18 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('group_persons', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 9, 16, 23, 776714, tzinfo=utc))),
                ('expiry', models.DateTimeField(blank=True)),
            ],
        ),
    ]
