# Generated by Django 3.2 on 2024-02-01 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('RON', 'RON')], default='RON', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='terms',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 1, 14, 33, 23, 152058, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, upload_to='payments/tickets'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='123', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 14, 33, 23, 152058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 1, 14, 33, 23, 152058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_series',
            field=models.CharField(default='DBPN1', max_length=5),
        ),
    ]
