# Generated by Django 3.2 on 2023-04-18 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 9, 17, 38, 379569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 9, 17, 38, 379538, tzinfo=utc)),
        ),
    ]
