# Generated by Django 3.2 on 2024-02-02 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20240201_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 41, 7, 94921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 2, 14, 41, 7, 94921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 2, 14, 41, 7, 94921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.BinaryField(),
        ),
    ]
