# Generated by Django 3.2 on 2024-02-02 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20240202_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_pdf',
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 47, 3, 739994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 2, 14, 47, 3, 739994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 2, 14, 47, 3, 739994, tzinfo=utc)),
        ),
    ]
