# Generated by Django 3.2 on 2024-02-03 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20240202_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 8, 12, 30, 720012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 8, 12, 30, 720012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 3, 8, 12, 30, 720012, tzinfo=utc)),
        ),
    ]
