# Generated by Django 3.2 on 2023-05-03 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20230503_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 8, 14, 56, 698076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 8, 14, 56, 698045, tzinfo=utc)),
        ),
    ]
