# Generated by Django 3.2 on 2023-05-03 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20230503_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 8, 15, 22, 150476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 8, 15, 22, 150444, tzinfo=utc)),
        ),
    ]
