# Generated by Django 3.2 on 2023-05-03 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20230503_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 8, 20, 57, 596319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 8, 20, 57, 596287, tzinfo=utc)),
        ),
    ]
