# Generated by Django 3.2 on 2025-05-16 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_auto_20240913_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 10, 48, 7, 767287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 14, 10, 48, 7, 767287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 16, 10, 48, 7, 767287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_nr',
            field=models.CharField(max_length=15),
        ),
    ]
