# Generated by Django 3.2 on 2025-05-16 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_auto_20250516_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 12, 31, 47, 314229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 14, 12, 31, 47, 314229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 16, 12, 31, 47, 314229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_nr',
            field=models.CharField(max_length=30),
        ),
    ]
