# Generated by Django 3.2 on 2023-05-09 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_auto_20230508_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='group_persons',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 9, 14, 30, 35, 325655, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_nr',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_series',
            field=models.CharField(default='a', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 7, 14, 30, 35, 325686, tzinfo=utc)),
        ),
    ]
