# Generated by Django 3.2 on 2023-05-09 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_auto_20230509_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(default=1234567, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='sum',
            field=models.IntegerField(default=35.5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 7, 15, 7, 39, 777311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 9, 15, 7, 39, 777277, tzinfo=utc)),
        ),
    ]
