# Generated by Django 3.2 on 2025-06-02 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_auto_20250523_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 15, 26, 31, 489093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 31, 15, 26, 31, 497897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 2, 15, 26, 31, 497897, tzinfo=utc)),
        ),
    ]
