# Generated by Django 3.2 on 2023-05-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_auto_20230510_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
