# Generated by Django 4.2.2 on 2023-08-23 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_delete_payment_alter_ticket_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('coin', models.CharField(default='RON', max_length=3)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 12, 37, 21, 159744, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 12, 37, 21, 158745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 12, 37, 21, 158745, tzinfo=datetime.timezone.utc)),
        ),
    ]
