# Generated by Django 4.2.2 on 2023-08-23 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_payment_alter_ticket_expiry_alter_ticket_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='coin',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON'), ('GBP', 'GBP'), ('CHF', 'CHF')], default='RON', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 15, 14, 34, 941946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 15, 14, 34, 940945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 15, 14, 34, 940945, tzinfo=datetime.timezone.utc)),
        ),
    ]
