# Generated by Django 4.2.2 on 2023-08-31 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_alter_payment_country_alter_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='terms',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 10, 30, 39, 788493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 29, 10, 30, 39, 787493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 10, 30, 39, 787493, tzinfo=datetime.timezone.utc)),
        ),
    ]
