# Generated by Django 4.2.2 on 2023-09-01 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_payment_terms_alter_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 9, 30, 16, 479936, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 9, 30, 16, 478935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 9, 30, 16, 478935, tzinfo=datetime.timezone.utc)),
        ),
    ]
