# Generated by Django 4.2.2 on 2023-09-01 09:57

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0048_remove_payment_slug_alter_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 9, 57, 21, 737991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 9, 57, 21, 734426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 9, 57, 21, 734426, tzinfo=datetime.timezone.utc)),
        ),
    ]
