# Generated by Django 4.1.11 on 2023-10-10 13:13

import datetime
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0077_delete_payment_alter_ticket_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON'), ('GBP', 'GBP'), ('CHF', 'CHF')], default='RON', max_length=3)),
                ('notes', models.TextField()),
                ('terms', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], default='pending', max_length=12)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 10, 10, 13, 13, 17, 674515, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 8, 13, 13, 17, 671517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 13, 13, 17, 671517, tzinfo=datetime.timezone.utc)),
        ),
    ]
