# Generated by Django 4.1.11 on 2023-11-02 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0078_payment_alter_ticket_expiry_alter_ticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('RON', 'RON')], default='RON', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 15, 34, 52, 954151, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 31, 15, 34, 52, 951285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 2, 15, 34, 52, 951285, tzinfo=datetime.timezone.utc)),
        ),
    ]
