# Generated by Django 4.1.11 on 2023-11-06 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0083_delete_ticket_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 9, 10, 8, 234004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_fname', models.CharField(max_length=100)),
                ('buyer_lname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_series', models.CharField(max_length=3)),
                ('ticket_nr', models.CharField(max_length=8)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 6, 9, 10, 8, 235005, tzinfo=datetime.timezone.utc))),
                ('expiry_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 4, 9, 10, 8, 235005, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
