# Generated by Django 4.1.11 on 2023-11-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0084_alter_payment_timestamp_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, upload_to='payments/tickets'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 11, 0, 38, 284538, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 4, 11, 0, 38, 285537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 6, 11, 0, 38, 285537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_series',
            field=models.CharField(default='DBPN1', max_length=5),
        ),
    ]
