# Generated by Django 4.1.11 on 2023-11-14 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0086_ticket_ticket_type_alter_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='quantity_kids',
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 8, 42, 57, 757948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 12, 8, 42, 57, 758946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 14, 8, 42, 57, 758946, tzinfo=datetime.timezone.utc)),
        ),
    ]
