# Generated by Django 4.1.11 on 2023-12-05 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0088_payment_bank_message_alter_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 8, 45, 56, 764117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 8, 45, 56, 765116, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 8, 45, 56, 765116, tzinfo=datetime.timezone.utc)),
        ),
    ]
