# Generated by Django 4.1.11 on 2023-12-06 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0100_alter_payment_timestamp_alter_ticket_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 10, 14, 54, 481783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 5, 10, 14, 54, 482783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 6, 10, 14, 54, 482783, tzinfo=datetime.timezone.utc)),
        ),
    ]
