# Generated by Django 4.1.11 on 2024-01-04 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0110_alter_payment_timestamp_alter_ticket_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 8, 34, 3, 220853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 3, 8, 34, 3, 221853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 4, 8, 34, 3, 221853, tzinfo=datetime.timezone.utc)),
        ),
    ]
