# Generated by Django 4.1.11 on 2024-01-27 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0146_alter_payment_timestamp_alter_ticket_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 15, 46, 28, 86517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 26, 15, 46, 28, 87517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 27, 15, 46, 28, 87517, tzinfo=datetime.timezone.utc)),
        ),
    ]
