# Generated by Django 4.1.2 on 2023-03-22 13:04

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Attraction Category',
                'verbose_name_plural': 'Attraction Categories',
            },
        ),
        migrations.CreateModel(
            name='PublicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField(max_length=3000)),
                ('link_ro', models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d %b %Y/')),
                ('link_en', models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d %b %Y/')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Public Document',
                'verbose_name_plural': 'Public Documents',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='testimonial_images')),
                ('text', ckeditor.fields.RichTextField(max_length=300)),
                ('status', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
