# Generated by Django 4.1.2 on 2023-03-22 13:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contact_subscriber_team_gallery_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='text_de',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publiccategory',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='job_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='job_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='job_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
