# Generated by Django 4.2 on 2023-06-20 10:21

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_partner_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='scouncil_images')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, max_length=254, null=True, upload_to='scouncil/')),
                ('text', models.TextField(max_length=300)),
                ('hierarchy', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scientific Council Member',
                'verbose_name_plural': 'Scientific Council Members',
            },
        ),
    ]
