# Generated by Django 3.2 on 2023-03-24 22:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_attraction_name_de_attraction_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField(max_length=3000)),
                ('link_ro', models.FileField(blank=True, max_length=254, null=True, upload_to='announcements/%d %b %Y/')),
                ('link_en', models.FileField(blank=True, max_length=254, null=True, upload_to='announcements/%d %b %Y/')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
        ),
    ]
