# Generated by Django 4.2 on 2023-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_scouncil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scouncil',
            name='text',
        ),
        migrations.AddField(
            model_name='scouncil',
            name='expert',
            field=models.CharField(default='geology', max_length=200),
            preserve_default=False,
        ),
    ]
