# Generated by Django 4.2.2 on 2023-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mngplandocscategory_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mngplancatlink',
            name='link',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/management_plan/%d_%b_%Y/'),
        ),
    ]
