# Generated by Django 4.1.2 on 2023-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_attraction_name_de_attraction_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
