# Generated by Django 3.2 on 2023-03-24 22:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text_de',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
