# Generated by Django 3.2 on 2023-03-24 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230324_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
