# Generated by Django 4.2.2 on 2023-08-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_mngplancatlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mngplancatlink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mngplandocscategory'),
        ),
        migrations.DeleteModel(
            name='CouncilCatLink',
        ),
        migrations.DeleteModel(
            name='CouncilDocsCategory',
        ),
    ]
