# Generated by Django 4.2 on 2023-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_scouncil_text_scouncil_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scouncil',
            old_name='expert',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='scouncil',
            name='interest_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scouncil',
            name='interest_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scouncil',
            name='interest_ro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
