# Generated by Django 4.1.2 on 2023-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_testimonial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_de',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_ro',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='text_de',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='text_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='text_ro',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
