# Generated by Django 4.2.2 on 2023-08-21 09:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_mngplancatlink_category_delete_councilcatlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkRegulationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Park Regulation Document',
                'verbose_name_plural': 'Park Regulation Documents',
            },
        ),
        migrations.CreateModel(
            name='ParkRegulationCatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('link', models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/park-regulation/%d_%b_%Y/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.parkregulationcategory')),
            ],
            options={
                'verbose_name': 'Park Regulation Link',
                'verbose_name_plural': 'Park Regulation Links',
                'ordering': ['-year'],
            },
        ),
    ]
