# Generated by Django 3.2 on 2023-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_announcement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
