# Generated by Django 4.2 on 2023-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_scouncil_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouncil',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
