# Generated by Django 3.2 on 2023-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20230324_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link_en',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='announcements/%d_%b_%Y/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_ro',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='announcements/%d_%b_%Y/'),
        ),
    ]
