# Generated by Django 4.2.2 on 2023-08-21 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_parkregulationcategory_parkregulationcatlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkregulationcategory',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='parkregulationcategory',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='parkregulationcategory',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='parkregulationcategory',
            name='title_de',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='parkregulationcategory',
            name='title_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='parkregulationcategory',
            name='title_ro',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
