# Generated by Django 4.2.2 on 2023-07-04 07:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_scouncil_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDocsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Council Document',
                'verbose_name_plural': 'Council Documents',
            },
        ),
        migrations.CreateModel(
            name='CouncilCatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('link', models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/%d_%b_%Y/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.publiccategory')),
            ],
            options={
                'verbose_name': 'Council Documents Link',
                'verbose_name_plural': 'Council Documents Links',
                'ordering': ['-year'],
            },
        ),
    ]
