# Generated by Django 4.1.2 on 2023-03-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blogpostcategory',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blogpostcategory',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
