# Generated by Django 3.2 on 2023-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20230325_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccategory',
            name='link_en',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d_%b_%Y/'),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='link_ro',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d_%b_%Y/'),
        ),
    ]
