# Generated by Django 4.2.2 on 2023-07-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_councildocscategory_councilcatlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilcatlink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.councildocscategory'),
        ),
    ]
