# Generated by Django 4.1.2 on 2023-03-22 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_blogpostcategory_title_de_blogpostcategory_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcategory',
            options={'verbose_name': 'Blog Post Category', 'verbose_name_plural': 'Blog Post Categories'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_ro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
