# Generated by Django 4.2.2 on 2023-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_wildlife_weight_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlife',
            name='height_max',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
