# Generated by Django 3.2 on 2023-03-27 09:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20230327_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccategory',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
