# Generated by Django 4.1.2 on 2023-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_blogpostcategory_options_blogpost_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attractioncategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(editable=False, max_length=255),
        ),
    ]
