# Generated by Django 4.2.2 on 2023-09-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_wildlife_height_max'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wildlife',
        ),
    ]
