# Generated by Django 4.2.2 on 2023-09-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_delete_wildlife'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wildlife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='wildlife_image')),
                ('text', models.TextField(max_length=2000)),
                ('height_max', models.IntegerField()),
                ('weight_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cons_status', models.CharField(choices=[('Endagered', 'Endagered'), ('Data Deficient', 'Data Deficient'), ('Least Concern', 'Least Concern'), ('Near Threatened', 'Near Threatened'), ('Vulnerable', 'Vulnerable'), ('Critically Endangered', 'Critically Endangered'), ('Extinct In The Wild', 'Extinct In The Wild'), ('Extinct', 'Extinct')], default='Least Concern', max_length=30)),
                ('life_span_max', models.IntegerField()),
                ('habitat', models.TextField(max_length=1000)),
                ('diet', models.CharField(max_length=300)),
                ('family', models.CharField(default='wildlife', editable=False, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.wildlifecategory')),
            ],
            options={
                'verbose_name': 'Wildlife species',
                'verbose_name_plural': 'Wildlife species',
            },
        ),
    ]
