# Generated by Django 3.2 on 2023-03-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_publiccategory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccategory',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='publiccategory',
            name='link_ro',
        ),
        migrations.RemoveField(
            model_name='publiccategory',
            name='year',
        ),
    ]
