# Generated by Django 4.1.2 on 2023-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_attraction_slug_alter_attractioncategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractioncategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attractioncategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='attractioncategory',
            name='name_ro',
        ),
        migrations.AlterField(
            model_name='attractioncategory',
            name='name_en',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
