# Generated by Django 4.1.2 on 2023-03-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_attractioncategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractioncategory',
            old_name='name_en',
            new_name='name',
        ),
    ]
