# Generated by Django 3.2 on 2023-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20230327_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_ro', models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d_%b_%Y/')),
            ],
            options={
                'verbose_name': 'Public link',
                'verbose_name_plural': 'Public links',
            },
        ),
    ]
