# Generated by Django 3.2 on 2023-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_publiccatlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicCatLink',
        ),
    ]
