# Generated by Django 4.2.2 on 2023-09-17 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_wildlife_diet_de_wildlife_diet_en_wildlife_diet_ro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
