# Generated by Django 4.1.7 on 2023-03-23 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractioncategory',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_de',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
