# Generated by Django 4.1.11 on 2023-10-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_event_expiry_alter_event_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
