# Generated by Django 3.2 on 2023-03-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_delete_publiccatlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('link_ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.publiccategory')),
            ],
            options={
                'verbose_name': 'Public link',
                'verbose_name_plural': 'Public links',
            },
        ),
    ]
