# Generated by Django 4.1.7 on 2023-03-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_attractioncategory_name_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
