# Generated by Django 4.1.11 on 2023-10-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_announcement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='timestamp',
        ),
    ]
