# Generated by Django 3.2 on 2023-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20230327_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccatlink',
            name='link_en',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='public_docs/%d_%b_%Y/'),
        ),
    ]
