# Generated by Django 4.1.7 on 2023-03-23 08:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100),
        ),
    ]
