# Generated by Django 4.1.11 on 2023-10-03 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_announcement_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
