# Generated by Django 3.2 on 2023-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_publiccatlink_link_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccatlink',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
