# Generated by Django 4.1.7 on 2023-03-23 09:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_event_slug_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='partner_images')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
        ),
    ]
