# Generated by Django 4.1.11 on 2023-10-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_announcement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
    ]
