# Generated by Django 3.2 on 2023-03-28 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_publiccatlink_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
