# Generated by Django 4.1.11 on 2023-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_announcement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_lname', models.CharField(max_length=100)),
                ('owner_fname', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('plate_nr', models.CharField(max_length=8)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
    ]
