# Generated by Django 3.2 on 2023-03-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20230328_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publiccatlink',
            options={'verbose_name': 'Public Documents Link', 'verbose_name_plural': 'Public Documents Links'},
        ),
    ]
