# Generated by Django 4.1.11 on 2024-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_vehiclecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Access areas',
                'verbose_name_plural': 'Access areas',
            },
        ),
    ]
