# Generated by Django 4.1.11 on 2024-01-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_accessarea_vehiclecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='...', max_length=1000, null=True)),
                ('identification_nr', models.CharField(max_length=20)),
                ('permit_nr', models.CharField(max_length=50)),
                ('permit_date', models.DateField(default='2024-01-03')),
                ('start_date', models.DateField(default='2024-01-03')),
                ('end_date', models.DateField(default='2024-12-31')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Allowed Vehicles',
                'verbose_name_plural': 'Allowed Vehicles',
            },
        ),
    ]
