# Generated by Django 4.1.11 on 2023-12-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_allowedvehicles_vehiclecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.vehiclecategory'),
            preserve_default=False,
        ),
    ]
