# Generated by Django 4.1.11 on 2023-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_allowedvehicles_categ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedvehicles',
            options={'verbose_name': 'Allowed Vehicles', 'verbose_name_plural': 'Allowed Vehicles'},
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
