# Generated by Django 4.1.11 on 2024-01-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_allowedvehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area_name', to='services.accessarea'),
            preserve_default=False,
        ),
    ]
