# Generated by Django 4.1.7 on 2023-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_attractioncategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractioncategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100),
        ),
    ]
