# Generated by Django 4.1.11 on 2024-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_allowedvehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='title_ro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
