# Generated by Django 3.2 on 2023-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20230328_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccatlink',
            name='link_en',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/%d_%b_%Y/'),
        ),
        migrations.AlterField(
            model_name='publiccatlink',
            name='link_ro',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/%d_%b_%Y/'),
        ),
    ]
