# Generated by Django 4.1.11 on 2023-12-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_allowedvehicles_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='slug',
        ),
    ]
