# Generated by Django 4.1.11 on 2024-01-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_vehiclecategory_title_de_vehiclecategory_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.accessarea'),
            preserve_default=False,
        ),
    ]
