# Generated by Django 3.2 on 2024-06-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_accessarea_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedvehicles',
            old_name='permit_date',
            new_name='timestamp',
        ),
    ]
