# Generated by Django 3.2 on 2023-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_publiccatlink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_de',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text_ro',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
