# Generated by Django 4.1.11 on 2023-12-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_allowedvehicles_permit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedvehicles',
            old_name='plate_nr',
            new_name='identification_nr',
        ),
    ]
