# Generated by Django 4.1.11 on 2024-01-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_allowedvehicles_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessarea',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
