# Generated by Django 3.2 on 2024-06-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_rename_permit_date_allowedvehicles_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
