# Generated by Django 3.2 on 2023-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20230406_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Flora Category',
                'verbose_name_plural': 'Flora Categories',
            },
        ),
        migrations.CreateModel(
            name='WildlifeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Wildlife Category',
                'verbose_name_plural': 'Wildlife Categories',
            },
        ),
    ]
