# Generated by Django 4.1.11 on 2023-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_rename_plate_nr_allowedvehicles_identification_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='identification_nr',
            field=models.CharField(max_length=20),
        ),
    ]
