# Generated by Django 3.2 on 2024-06-07 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_alter_allowedvehicles_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
