# Generated by Django 4.1.11 on 2024-01-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_accessarea_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedvehicles',
            name='area',
        ),
    ]
