# Generated by Django 3.2 on 2023-04-06 14:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_floracategory_wildlifecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wildlife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='wildlife_images')),
                ('text', models.TextField(max_length=2000)),
                ('weight_min', models.IntegerField()),
                ('weight_max', models.IntegerField()),
                ('cons_status', models.CharField(choices=[('Endagered', 'Endagered'), ('Data Deficient', 'Data Deficient'), ('Least Concern', 'Least Concern'), ('Near Threatened', 'Near Threatened'), ('Vulnerable', 'Vulnerable'), ('Critically Endangered', 'Critically Endangered'), ('Extinct In The Wild', 'Extinct In The Wild'), ('Extinct', 'Extinct')], default='Least Concern', max_length=30)),
                ('life_span_min', models.IntegerField()),
                ('life_span_max', models.IntegerField()),
                ('habitat', models.TextField(max_length=1000)),
                ('diet', multiselectfield.db.fields.MultiSelectField(choices=[('Fish', 'Fish'), ('Deer', 'Deer'), ('wild boar', 'wild boar'), ('grass', 'grass'), ('larvae', 'larvae'), ('nuts', 'nuts'), ('seeds', 'seeds'), ('snakes', 'snakes'), ('frogs', 'frogs'), ('small birds', 'small birds'), ('fruits', 'fruits'), ('roots', 'roots'), ('bark', 'bark'), ('insects', 'insects'), ('small rodents', 'small rodents')], max_length=20)),
                ('family', models.CharField(default='wildlife', editable=False, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.wildlifecategory')),
            ],
            options={
                'verbose_name': 'Wildlife species',
                'verbose_name_plural': 'Wildlife species',
            },
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='flora_images')),
                ('text', models.TextField(max_length=2000)),
                ('height_max', models.IntegerField()),
                ('flowering_start', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='April', max_length=30)),
                ('flowering_end', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='September', max_length=30)),
                ('cons_status', models.CharField(choices=[('Endagered', 'Endagered'), ('Data Deficient', 'Data Deficient'), ('Least Concern', 'Least Concern'), ('Near Threatened', 'Near Threatened'), ('Vulnerable', 'Vulnerable'), ('Critically Endangered', 'Critically Endangered'), ('Extinct In The Wild', 'Extinct In The Wild'), ('Extinct', 'Extinct')], default='Least Concern', max_length=30)),
                ('life_span', models.CharField(choices=[('Annual', 'Annual'), ('Perennial', 'Perennial'), ('Biennial', 'Biennial')], default='Annual', max_length=30)),
                ('habitat', models.TextField(max_length=1000)),
                ('family', models.CharField(default='flora', editable=False, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.floracategory')),
            ],
            options={
                'verbose_name': 'Flora species',
                'verbose_name_plural': 'Flora species',
            },
        ),
    ]
