# Generated by Django 3.2 on 2024-06-07 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_allowedvehicles_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='allowedvehicles',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
