# Generated by Django 4.1.11 on 2023-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_allowedvehicles_identification_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='slug_de',
            field=models.SlugField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='slug_en',
            field=models.SlugField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='slug_ro',
            field=models.SlugField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
