# Generated by Django 3.2 on 2024-06-07 06:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20240607_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
        migrations.AlterField(
            model_name='allowedvehicles',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='allowedvehicles',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
