# Generated by Django 4.1.11 on 2023-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_vehiclecategory_slug_vehiclecategory_slug_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_de',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_ro',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
