# Generated by Django 3.2 on 2023-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_flora_wildlife'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='text_de',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='text_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='text_ro',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='floracategory',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='floracategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='floracategory',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='text_de',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='text_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='text_ro',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='wildlifecategory',
            name='name_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlifecategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wildlifecategory',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
