# Generated by Django 3.2 on 2023-04-06 15:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20230406_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlife',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fish', 'Fish'), ('Deer', 'Deer'), ('wild boar', 'wild boar'), ('grass', 'grass'), ('leaves', 'leaves'), ('larvae', 'larvae'), ('nuts', 'nuts'), ('seeds', 'seeds'), ('snakes', 'snakes'), ('frogs', 'frogs'), ('small birds', 'small birds'), ('fruits', 'fruits'), ('roots', 'roots'), ('bark', 'bark'), ('insects', 'insects'), ('small rodents', 'small rodents')], max_length=20),
        ),
    ]
