# Generated by Django 4.1.11 on 2023-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_vehiclecategory_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedvehicles',
            old_name='owner_fname',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='allowedvehicles',
            name='owner_lname',
        ),
        migrations.AlterField(
            model_name='allowedvehicles',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
