# Generated by Django 3.2 on 2023-04-06 15:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_wildlife_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlife',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fish', 'Fish'), ('Deer', 'Deer'), ('wild boar', 'wild boar'), ('grass', 'grass'), ('leaves', 'leaves'), ('buds', 'buds'), ('larvae', 'larvae'), ('nuts', 'nuts'), ('seeds', 'seeds'), ('snakes', 'snakes'), ('frogs', 'frogs'), ('small birds', 'small birds'), ('fruits', 'fruits'), ('roots', 'roots'), ('bark', 'bark'), ('insects', 'insects'), ('small rodents', 'small rodents')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wildlife',
            name='image',
            field=models.ImageField(blank=True, upload_to='wildlife_image'),
        ),
    ]
