# Generated by Django 3.2 on 2024-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20240705_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='access_area', to='services.AccessArea'),
        ),
    ]
