# Generated by Django 4.1.11 on 2023-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_rename_owner_fname_allowedvehicles_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_de',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug_ro',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='title_ro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
