# Generated by Django 3.2 on 2023-04-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20230406_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='image',
            field=models.ImageField(blank=True, upload_to='flora_image'),
        ),
    ]
