# Generated by Django 3.2 on 2025-05-15 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_allowedvehicles_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatReservesDocsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Natural Reserves Document',
                'verbose_name_plural': 'Natural Reserves Documents',
            },
        ),
        migrations.AlterField(
            model_name='allowedvehicles',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
        ),
        migrations.CreateModel(
            name='NatReservesCatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('link', models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/natural_reserves/%d_%b_%Y/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.natreservesdocscategory')),
            ],
            options={
                'verbose_name': 'Natural Reserves Documents Link',
                'verbose_name_plural': 'Natural Reserves Documents Links',
                'ordering': ['-year'],
            },
        ),
    ]
