# Generated by Django 4.1.11 on 2023-12-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_vehiclecategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='slug_de',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='slug_ro',
        ),
    ]
