# Generated by Django 3.2 on 2023-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_flora_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlife',
            name='diet',
            field=models.CharField(max_length=300),
        ),
    ]
