# Generated by Django 4.1.11 on 2023-12-13 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_remove_vehiclecategory_slug_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowedvehicles',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
