# Generated by Django 3.2 on 2025-05-15 07:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_auto_20250515_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='title_de',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='title_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='natreservesdocscategory',
            name='title_ro',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
