# Generated by Django 3.2 on 2023-04-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_wildlife_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlife',
            name='diet_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='diet_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='diet_ro',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
