# Generated by Django 3.2 on 2025-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20250515_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Average', 'Average'), ('Average to Difficult', 'Average to Difficult'), ('Easy to Average', 'Easy to Average')], max_length=30)),
                ('coordinates', models.TextField(help_text='List of coordinates (in Pulkovo/Stereo70 format separated by commas)')),
                ('gpx_file', models.FileField(upload_to='gps_tracks/')),
            ],
        ),
    ]
