# Generated by Django 4.1.11 on 2024-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_allowedvehicles_end_date_allowedvehicles_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='area',
            field=models.CharField(default='Dichiu', max_length=50),
            preserve_default=False,
        ),
    ]
