# Generated by Django 4.1.11 on 2024-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_allowedvehicles_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
