# Generated by Django 3.2 on 2023-04-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20230406_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='habitat_de',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='habitat_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='habitat_ro',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='habitat_de',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='habitat_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='habitat_ro',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
