# Generated by Django 3.2 on 2025-05-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_themetrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themetrail',
            name='coordinates',
        ),
    ]
