# Generated by Django 4.1.11 on 2024-01-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_alter_allowedvehicles_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedvehicles',
            name='permit_date',
        ),
    ]
