# Generated by Django 3.2 on 2023-04-12 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20230412_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
