# Generated by Django 3.2 on 2025-06-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_remove_themetrail_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='text_ro',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_ro',
        ),
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='title_ro',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
