# Generated by Django 3.2 on 2025-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_auto_20250602_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
