# Generated by Django 4.1.11 on 2024-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_remove_allowedvehicles_permit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='description',
            field=models.TextField(blank=True, default='...', max_length=1000, null=True),
        ),
    ]
