# Generated by Django 3.2 on 2023-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link_en',
            field=models.FileField(blank=True, default='a', max_length=254, upload_to='announcements/%d_%b_%Y/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_ro',
            field=models.FileField(blank=True, default='a', max_length=254, upload_to='announcements/%d_%b_%Y/'),
            preserve_default=False,
        ),
    ]
