# Generated by Django 3.2 on 2025-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_delete_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostCategory',
        ),
    ]
