# Generated by Django 4.1.11 on 2024-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_alter_allowedvehicles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedvehicles',
            name='permit_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
