# Generated by Django 4.1.11 on 2024-01-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_allowedvehicles_permit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='area',
            field=models.CharField(choices=[('General access', 'General access'), ('Area 2', 'Area 2'), ('Area 3', 'Area 3'), ('Area 4', 'Area 4'), ('Area 5', 'Area 5'), ('Area 6', 'Area 6'), ('Area 7', 'Area 7')], max_length=50),
        ),
    ]
