# Generated by Django 3.2 on 2023-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20230413_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link_en',
            field=models.FileField(blank=True, max_length=254, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_ro',
            field=models.FileField(blank=True, max_length=254, upload_to='announcements/'),
        ),
    ]
