# Generated by Django 4.2.11 on 2025-06-17 13:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_delete_blogpostcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=tinymce.models.HTMLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_de',
            field=tinymce.models.HTMLField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_en',
            field=tinymce.models.HTMLField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_ro',
            field=tinymce.models.HTMLField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='mngplandocscategory',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mngplandocscategory',
            name='text_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='mngplandocscategory',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='mngplandocscategory',
            name='text_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='natreservesdocscategory',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='natreservesdocscategory',
            name='text_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='natreservesdocscategory',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='natreservesdocscategory',
            name='text_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='parkregulationcategory',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='parkregulationcategory',
            name='text_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='parkregulationcategory',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='parkregulationcategory',
            name='text_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='parkrules',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='publiccategory',
            name='text_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
