# Generated by Django 4.2.11 on 2025-06-17 15:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_alter_announcement_text_alter_announcement_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedvehicles',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='...', max_length=1000, null=True),
        ),
    ]
