# Generated by Django 3.2 on 2023-05-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20230503_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
