# Generated by Django 3.2 on 2023-05-03 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_auto_20230503_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expiry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
