# Generated by Django 3.2 on 2023-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20230503_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sector',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
