# Generated by Django 3.2 on 2023-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_team_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sector_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sector_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sector_ro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
