# Generated by Django 3.2 on 2023-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20230508_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlife',
            name='life_span_min',
        ),
        migrations.RemoveField(
            model_name='wildlife',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='wildlife',
            name='weight_min',
        ),
    ]
