# Generated by Django 3.2 on 2023-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20230510_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(upload_to='attraction_images'),
        ),
    ]
