# Generated by Django 3.2 on 2023-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_parkrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
