# Generated by Django 3.2 on 2023-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_partner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
