# Generated by Django 4.2 on 2023-06-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_partner_title_de_partner_title_en_partner_title_ro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='title_ro',
        ),
    ]
