# Generated by Django 3.2 on 2024-09-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='access_and_rules_compliance.lawcategory'),
            preserve_default=False,
        ),
    ]
