# Generated by Django 3.2 on 2024-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0003_auto_20240903_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'verbose_name': 'Law', 'verbose_name_plural': 'Laws'},
        ),
        migrations.AlterModelOptions(
            name='lawcategory',
            options={'verbose_name': 'Legislation category', 'verbose_name_plural': 'Legislation category'},
        ),
        migrations.AddField(
            model_name='law',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False),
        ),
    ]
