# Generated by Django 3.2 on 2024-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0004_auto_20240913_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='link',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='public_docs/legislation/%d_%b_%Y/'),
        ),
    ]
