# Generated by Django 3.2 on 2024-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0005_law_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
