# Generated by Django 3.2 on 2024-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0006_alter_law_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='doc_nr',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
