# Generated by Django 3.2 on 2024-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0007_law_doc_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=500),
        ),
    ]
