# Generated by Django 3.2 on 2024-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0008_alter_law_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='doc_type',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
