# Generated by Django 3.2 on 2024-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_and_rules_compliance', '0009_law_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='doc_type',
            field=models.CharField(max_length=100),
        ),
    ]
